language: node_js
node_js:
    - "10"                   # Maintenance LTS release
    - "12"                   # Active LTS release
    - "14"                   # Current
cache:
   npm: false
script:
    make all
before_install:
    make clean
after_success:
    make report-coverage
