language: node_js
node_js:
    - "6"                    # Maintenance LTS release
    - "8"                    # Maintenance LTS release
    - "10"                   # Active LTS release
    - "node"                 # Latest stable release
cache:
   npm: false
script:
    make all
before_install:
    make clean
after_success:
    make report-coverage
