language: node_js
node_js:
    - "22"                   # Maintenance LTS release
    - "24"                   # Active LTS release
    - "26"                   # Current
cache:
   npm: false
script:
    make all
before_install:
    make clean
after_success:
    make report-coverage
