language: node_js
node_js:
    - "10"                   # Maintenance LTS release
    - "12"                   # Active LTS release
    # TODO(mmarchini): Tests are failing on v14. Need to make the package/tests
    # compatible before re-enabling it.
    # - "node"                 # Latest stable release
cache:
   npm: false
script:
    make all
before_install:
    make clean
after_success:
    make report-coverage
