language: node_js
script:
    make prepush
node_js:
    - "4"                    # Maintenance LTS release
    - "lts/*"                # Active LTS release
    - "node"                 # Latest stable release
after_success:
    - make report-coverage
    - make nsp
