---
name: Conventional Commit Linter
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: wagoid/commitlint-github-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
