on:
  push:
    branches:
      - master
      # For previous major branches, like v2.x, v3.x, etc.
      # If branch doesn't exist and you need a release on that major, create
      # one from the latest tag for that major
      - v*.x

name: releaser

permissions:
  contents: write
  pull-requests: write

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: 26
        if: ${{ steps.release.outputs.release_created }}
      - run: npm install
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish --token=${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
